apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkusbr 
spec:
  selector:
    matchLabels:
      app: quarkusbr
  template:
    metadata:
      labels:
        app: quarkusbr
    spec:
      containers:
        - image: okteto.dev/java-gradle-quarkusbr:1.0.0
          name: quarkusbr

---

apiVersion: v1
kind: Service
metadata:
  name: quarkusbr
spec:
  type: ClusterIP
  ports:
    - name: "quarkusbr"
      port: 8080
  selector:
    app: quarkusbr

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkusbr
  annotations:
    dev.okteto.com/generate-host: quarkusbr
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: quarkusbr
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific